import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
   en:{
      quran: "Quran",
      settings: "Settings",
      close: "Close",
      readSurah: "Read the surah",
      continue: "Continue",
      watchVideo: "Watch video",
      hideVideo: "Hide video",
      saveToBookmarks: "Save to bookmarks",
      sura: "Sura",
      copy: "Copy",
      share: "Share",
      suggestTranslation: "Suggest a translation",
      comment: "Comment",
      send: "Send",
      enterYourEmail: "Enter your e-mail",
      message: "Message",
      yourVersionTranslation: "Write your version of the translation",
      closeComment: "Close comment",
      favorite: "Favorite",
      removeFromFavorite: "Remove from favorites",
      confirmDeletingFromFavorite: "Are you sure you want to remove the ayat from the favorites?",
      youCanAgainAddToFavorite: "You can add it again at any time.",
      cancel: "Cancel",
      delete: "Delete",
      fontSize: "Font size",
      textAlignment: "Alignment of source text",
      favoritesAndBookmarks: "Favorites and bookmarks",
      clearFavorite: "Clear your favorites",
      deleteAllBookmarks: "Delete all bookmarks",
      deleteAllNotifications: "Delete all notifications",
      appLanguage: "Application language",
      version: "Version",
      help: "Help",
      writeReview: "Write a review",
      reportProblem: "Report a problem",
      supportedDevices: "Supported iOS devices and versions",
      sourceAndTranslation: "Source and translation",
      bookmark: "Bookmark",
      somethingIsNoWorking: "Something not working?",
      explainWhatHappened: "Briefly explain what happened.",
      writeWhatDoesNotWork: "Write what doesn't work...",
      writeYourReview: "Write your review",
      sentSuccessfully: "Your message sent successfully.",
      weWillImmediatelySendNotification: "As soon as we can solve your problem, we will immediately send a notification to your email.",
      arabicName: "Arabic name",
      numberOfAyats: "Number of ayats",
      numberOfWords: "Number of words",
      place: "A place of revelation",
      order: "Chronological order",
      leftAlignment: "left side",
      rightAlignment: "right side",
      chooseFontSize: 'Choose font size',
      commentariesOnAyat: "Commentaries on Ayat",
      noComment: "There is no comment"
   },
   ua: {
      quran: "Коран",
      settings: "Налаштування",
      close: "Закрити",
      readSurah: "Читати суру",
      continue: "Продовжити",
      watchVideo: "Переглянути відео",
      hideVideo: "Приховати відео",
      saveToBookmarks: "Зберегти в закладки",
      sura: "Сура",
      copy: "Скопіювати",
      share: "Поділитися",
      suggestTranslation: "Запропонувати переклад",
      comment: "Коментар",
      send: "Відправити",
      enterYourEmail: "Вкажіть ваш e-mail",
      message: "Повідомлення",
      yourVersionTranslation: "Напишіть ваш варіант перекладу",
      closeComment: "Закрити коментар",
      favorite: "Обране",
      removeFromFavorite: "Видалити з обраного",
      confirmDeletingFromFavorite: "Ви дійсно бажаєте видалити аят із обраного?",
      youCanAgainAddToFavorite: "Ви зможете його знову додати у будь-який момент.",
      cancel: "Скасувати",
      delete: "Видалити",
      fontSize: "Розмір шрифту",
      textAlignment: "Вирівнювання вихідного тексту",
      favoritesAndBookmarks: "Обране та закладки",
      clearFavorite: "Очистити обране",
      deleteAllBookmarks: "Видалити усі закладки",
      deleteAllNotifications: "Видалити усі сповіщення",
      appLanguage: "Мова додатку",
      version: "Версія",
      help: "Допомога",
      writeReview: "Написати відгук",
      reportProblem: "Повідомити про проблему",
      supportedDevices: "Підтримувані пристрої та версії iOS",
      sourceAndTranslation: "Джерело та переклад",
      bookmark: "Закладка",
      writeYourReview: "Напишіть Ваш відгук",
      somethingIsNoWorking: "Щось не працює?",
      explainWhatHappened: "Коротко поясніть, що сталося.",
      writeWhatDoesNotWork: "Напишіть, що не працює...",
      sentSuccessfully: "Ваше повідомлення успішно відправлене.",
      weWillImmediatelySendNotification: "Як тільки ми зможемо вирішити Вашу проблему, ми одразу надішлимо інформацію на вашу електронну пошту.",
      arabicName: "Арабська назва",
      numberOfAyats: "Кількість аятів",
      numberOfWords: "Кількість слів",
      place: "Місце одкровення",
      order: "Хронологічний порядок",
      leftAlignment: "По лівому краю",
      rightAlignment: "По правому краю",
      chooseFontSize: 'Оберіть розмір шрифту',
      commentariesOnAyat: "Коментарі до Аят",
      noComment: "Немає жодного коментаря"
   }
});